// <auto-generated />
using Code.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Code.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250521112801_addForeignKeyForClipProductRelation")]
    partial class addForeignKeyForClipProductRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Code.Models.Clips", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "In this video we are going to talk about lists in Python",
                            Name = "Python Lists"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Let's dive into Java , not the coffee! The ultimate course for learning Java is here",
                            Name = "Java Introduction"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The power of web designing is here , learn ASP.NET Core now!",
                            Name = "ASP.NET Core"
                        });
                });

            modelBuilder.Entity("Code.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClipsId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClipsId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Ali",
                            ClipsId = 1,
                            Description = "This is Aliz. book",
                            ISBN = "Qrssww123",
                            ListPrice = 100.0,
                            Price = 1000.0,
                            Price100 = 50.0,
                            Price50 = 12.0,
                            Title = "Aliz in Jungle"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ili",
                            ClipsId = 1,
                            Description = "This is Iliz. book",
                            ISBN = "Q233ssww123",
                            ListPrice = 100.0,
                            Price = 1000.0,
                            Price100 = 50.0,
                            Price50 = 12.0,
                            Title = "Iliz in Jungle"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Gholi",
                            ClipsId = 2,
                            Description = "This is Gholiz. book",
                            ISBN = "adfadrssww123",
                            ListPrice = 100.0,
                            Price = 1000.0,
                            Price100 = 50.0,
                            Price50 = 12.0,
                            Title = "Gholliz in Jungle"
                        });
                });

            modelBuilder.Entity("Code.Models.Product", b =>
                {
                    b.HasOne("Code.Models.Clips", "clips")
                        .WithMany()
                        .HasForeignKey("ClipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clips");
                });
#pragma warning restore 612, 618
        }
    }
}
